---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./networking
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
