---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: yelb
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deployments/platformdeployment/Kubernetes/yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: yelb
  validation: client

